name: Bug
description: Something is broken
labels: ["type:bug", "status:needs-triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
